<?php
$labels = array(
    'roundcube_2fa_title' => 'Two Factor Authentication',
    'roundcube_2fa_code_label' => 'Enter the code from your authenticator app',
    'roundcube_2fa_invalid' => 'Invalid code, please try again',
    'roundcube_2fa_setup_title' => 'Set up Two-Factor Authentication',
    'roundcube_2fa_disable_title' => '2FA Disabled',
    'roundcube_2fa_scan_qr' => 'Scan this QR code with your Authenticator app',
    'roundcube_2fa_confirm' => 'Confirm',
);
