<?php
$labels = array(
    'roundcube_2fa_title' => 'Autenticação em 2 fatores',
    'roundcube_2fa_code_label' => 'Digite o código do seu app autenticador',
    'roundcube_2fa_invalid' => 'Código inválido, tente novamente',
    'roundcube_2fa_setup_title' => 'Configurar autenticação em 2 fatores',
    'roundcube_2fa_disable_title' => '2FA desativado',
    'roundcube_2fa_scan_qr' => 'Escaneie este QR code com seu app autenticador',
    'roundcube_2fa_confirm' => 'Confirmar',
);
